version: '3.9'
services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    depends_on:
      - db
    hostname: dash
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres
    ports:
      - 8001:80
    networks:
      - stride
  db:
    image: postgres:latest
    container_name: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 54321:5432
    networks:
      - stride
  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile
    container_name: loader
    networks:
      - stride
    volumes:
      - ./data:/data
networks:
  stride:
    driver: bridge
